### ISSUE TITLE
wrong version name in 1.0.3 release

### ISSUE THREAD

**Issue by rriemann** [allotropia/nextcloud_files_libreoffice_edit#10]
Hi!

Thanks for your work on this useful tool. I still fight to make it work in my setup. While researching I noticed that the appinfo/info.xml says version ` <version>1.0.2</version>` in the latest 1.0.3 I downloaded from `https://github.com/allotropia/nextcloud_files_libreoffice_edit/releases/download/v1.0.3/fileslibreofficeedit.tar.gz`.

**Comment by smehrbrodt** [comment]
Thanks for the hint!
I uploaded a new release, 1.0.4 which should now have the correct version number in appinfo/info.xml.

Let me know it this works for you.
