### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by JordanDIG** [allotropia/nextcloud_files_libreoffice_edit#12]
Hello,

I changed the name of the button "Edit with libreoffice" in the file script.js to line 46
But this modification is not reflected on nextcloud, I tried to make a make in the application folder but this command returns that no operation was made.

**Comment by JordanDIG** [comment]
> You want that label to be translated? Is that the request?

Yes I would like to translate it

**Comment by smehrbrodt** [comment]
Ok, this app needs setting up for translating according to https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations

Let me know if you want to help with setting this up.

**Comment by JordanDIG** [comment]
> Ok, this app needs setting up for translating according to https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
> 
> Let me know if you want to help with setting this up.

I don't understand how to do it, can you help me?

**Comment by JordanDIG** [comment]
For my problem of modification not taken into account it was simply necessary to wait.

**Comment by JordanDIG** [comment]
@smehrbrodt

**Comment by smehrbrodt** [comment]
@JordanDIG PR from @Valdnet was merged - feel free to add your translations to the l10n directory as suggested.

@Valdnet Do you have any documentation how to set this project up for translation in Transifex? Do you want to help with setting this up?

**Comment by JordanDIG** [comment]
Hello,
I have created a pull request [https://github.com/allotropia/nextcloud_files_libreoffice_edit/pull/14](https://github.com/allotropia/nextcloud_files_libreoffice_edit/pull/14) to add french

**Comment by Valdnet** [comment]
> Do you have any documentation how to set this project up for translation in Transifex?

Follow this [documentation](https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html) 😉.

**Comment by smehrbrodt** [comment]
Ok, I started the setup. Here's the request: https://github.com/nextcloud/docker-ci/issues/400

**Comment by smehrbrodt** [comment]
Transifex is now set up.
I added a link to the readme: https://github.com/allotropia/nextcloud_files_libreoffice_edit/blob/master/README.md#translations

**Comment by Valdnet** [comment]
Good job 👍. Already translated into Polish 😉.

**Comment by smehrbrodt** [comment]
Nice, will publish a new release in 1 or 2 weeks when some translations have poured in.

**Comment by Valdnet** [comment]
OK. Translations will appear very quickly in many languages 😉.

**Comment by Valdnet** [comment]
Works correctly 👍.
