### ISSUE TITLE
Can't save files due to file lock

### ISSUE THREAD

**Issue by danir-de** [allotropia/nextcloud_files_libreoffice_edit#16]
When using [nextcloud/files_lock](https://github.com/nextcloud/files_lock), you can't edit files you opened via the extension.
LibreOffice states that the file cannot be saved since it's locked.

The Nextcloud log prints:

`Fatal | webdav | Sabre\DAV\Exception\Locked`

Nextcloud 24.0.3
Files Lock 24.0.1

**Comment by smehrbrodt** [comment]
What should the extension do in this case?

**Comment by danir-de** [comment]
I'm not entirely sure on the technical side, but It would be able to actually save the changes you've done via WebDAV.

If it's not related to this extension at all, please close.

**Comment by smehrbrodt** [comment]
So the file was unlocked, then it was opened in LO with the "Edit with LibreOffice" context menu entry, and saving doesn't work in LO?

**Comment by danir-de** [comment]
✅ Correct.

**Comment by smehrbrodt** [comment]
Can you please report this issue to https://github.com/nextcloud/files_lock ?
This extension doesn't really do anything, so I don't think the problem is on this side.
