### ISSUE TITLE
Libreoffice 

### ISSUE THREAD

**Issue by earendil1** [allotropia/nextcloud_files_libreoffice_edit#22]
Actual behavior: selecting Open with LIbreoffice on NC from the dropdown menu of an odt file opens Libreoffice but not the file.
Desired behavior: should open the file.
Reproduce: Try to open a file with the following configuration

Thanks!

Mac 
Monterey
12.6

Chrome
Versione 106.0.5249.119 (Build ufficiale) (arm64)

LibreOffice
Version: 7.4.2.3 / LibreOffice Community
Build ID: 382eef1f22670f7f4118c8c2dd222ec7ad009daf
CPU threads: 8; OS: Mac OS X 12.6; UI render: default; VCL: osx
Locale: it-IT (it_IT.UTF-8); UI: en-US
Calc: threaded

**Comment by smehrbrodt** [comment]
This is a known problem, see #6
