### ISSUE TITLE
How to make this work with MFA and/or U2F?

### ISSUE THREAD

**Issue by ehuelsmann** [allotropia/nextcloud_files_libreoffice_edit#24]
Hi,

I've got MFA and U2F installed on my account. Filling out the password for my account doesn't provide me with access to the file, but keeps asking for my password. What should I do to use this functionality in my setup?

Regards,

Erik.

**Comment by itProfi** [comment]
Was same problem.  Create an app password (Nextcloud Settings -> Security) - all work great!
