### ISSUE TITLE
Error opening libreoffice

### ISSUE THREAD

**Issue by wuaralax** [allotropia/nextcloud_files_libreoffice_edit#25]
when selecting the option to edit with libre office, writer loads, however it does not load the box where I must enter my credentials, then the software closes
This on nextcloud 25 - php 8.0 and debian 10

Thanks in advance for this project and your work

https://user-images.githubusercontent.com/9514470/222447627-c4f2c31f-fe98-4899-924c-8912a7f7cf52.mp4

**Comment by smehrbrodt** [comment]
Is there an soffice.bin process still running?
Can you start LibreOffice manually?

**Comment by wuaralax** [comment]
Yea libreoffice start without any problem in my computer.
I don't see any process related to soffice process. 
We check in two computers and occurs the same thing.

https://user-images.githubusercontent.com/9514470/222458935-e23ac335-4388-492b-9774-88f7d060470d.mp4

**Comment by smehrbrodt** [comment]
Which LibreOffice version is that?

**Comment by wuaralax** [comment]
This :

Version: 7.5.0.3 (X86_64) / LibreOffice Community
Build ID: c21113d003cd3efa8c53188764377a8272d9d6de
CPU threads: 8; OS: Windows 10.0 Build 19044; UI render: Skia/Raster; VCL: win
Locale: es-CL (es_CL); UI: es-ES
Calc: threaded

**Comment by smehrbrodt** [comment]
Looks like LibreOffice is crashing then.
Are there any files in `%appdata%\LibreOffice\4\crash` ?

**Comment by wuaralax** [comment]
There's a dump.ini file, this is the content of the file.


ProductName=LibreOffice
Version=7.5.0.3
BuildID=c21113d003cd3efa8c53188764377a8272d9d6de
URL=https://crashreport.libreoffice.org/submit/
Proxy=http:0
UseSkia=true
Language=es-CL
CPUModelName=Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
CPUFlags=sse3 pclmulqdq monitor ssse3 fma cpmxch16b sse41 sse42 movbe popcnt aes xsave osxsave avx f16c rdrand msr cx8 sep cmov clfsh mmx fxsr sse sse2 ht fsgsbase bmi1 avx2 bmi2 erms invpcid rdseed adx lahf abm syscall rdtscp
MemoryTotal=8221704 kB
ShutDown=true


ProductName=LibreOffice
Version=7.5.0.3
BuildID=c21113d003cd3efa8c53188764377a8272d9d6de
URL=https://crashreport.libreoffice.org/submit/
Proxy=http:0
UseSkia=true
Language=es-CL
CPUModelName=Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
CPUFlags=sse3 pclmulqdq monitor ssse3 fma cpmxch16b sse41 sse42 movbe popcnt aes xsave osxsave avx f16c rdrand msr cx8 sep cmov clfsh mmx fxsr sse sse2 ht fsgsbase bmi1 avx2 bmi2 erms invpcid rdseed adx lahf abm syscall rdtscp
MemoryTotal=8221704 kB
ShutDown=true

**Comment by smehrbrodt** [comment]
Nothing useful then.
You can try resetting the user profile https://wiki.documentfoundation.org/UserProfile
