### ISSUE TITLE
Cannot pass login/password prompt

### ISSUE THREAD

**Issue by Randerspl** [allotropia/nextcloud_files_libreoffice_edit#27]
Hello, it is a nice idea for a plugin but i have a problem after installation.

I installed it and it seems to connect via webdav to libreoffice because it starts to open program (i'm using windows 10 on computer with libreoffice v7.6.2.1 ).
Then it asked for login/password and then to set libreoffice password. But when i entered for second prompt i got new prompt with "wrong password".
I think its not possible for me to paste wrong password because i'm using password manager and this password is currently used to login via browser.

But i have two ideas why this happens. In libreoffice prompt it shows that my instance is on "www.domain.com" but my instance is really on "www.domain.com/nextcloud" so first idea is that its using wrong URL for credentials.
Second element is that i have installed "Two-Factor TOTP Provider" application which can block simple login/password attempts.

**Comment by smehrbrodt** [comment]
You need to add an app password to Nextcloud if you have 2FA enabled.

**Comment by Randerspl** [comment]
Than you very much, i didn't know about it.
