### ISSUE TITLE
Question : is file locked while being edited?

### ISSUE THREAD

**Issue by manu-p** [allotropia/nextcloud_files_libreoffice_edit#28]
Thanks for the app. Just one question: on a group folder one might want to edit a file being edited by another user...

Is there a lock on the currently edited document so that no one can edit it while it's opened by someone else?

**Comment by smehrbrodt** [comment]
Yes, if you have the [files_lock](https://apps.nextcloud.com/apps/files_lock) plugin installed it will be locked when it's open in LibreOffice.
