### ISSUE TITLE
Dropdown menu not present

### ISSUE THREAD

**Issue by firmans22** [allotropia/nextcloud_files_libreoffice_edit#29]
After right clicking excell file the menu "Edit with LibreOffice" not show at drop down menu, this happening after i upgrading nextcloud to latest version of 28.0.1

**Comment by willdapperdata** [comment]
This is also true for me on all file types

**Comment by descubriendoelcodigo** [comment]
just reporting, same here

**Comment by mhazan01** [comment]
same issue here with nc (28.0.3)

**Comment by rriemann** [comment]
same here with version 28.0.3

**Comment by joshtrichards** [comment]
From the looks of it, it's unclear whether this app has been updated for Nc v28:

https://github.com/allotropia/nextcloud_files_libreoffice_edit/blob/23e0a6f2f1c6911adda457af570434c1e702c4d0/appinfo/info.xml#L24

Looks like it was hardcoded to indicate support of future versions of Nextcloud Server ahead of time. :) That doesn't mean it's been adapted for these versions unfortunately.

**Comment by firmans22** [comment]
Until this issue resolved then this app is useless

**Comment by mhazan01** [comment]
is there a way to get the app removed from the store for 28.x ? or is there an alternative ?

**Comment by Darkless012** [comment]
There is new API to define FileActions in Nextcloud 28
and also removed API which is used by this plugin.
see: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html

**Comment by mhazan01** [comment]
still not working with nc29.0.0

**Comment by hhlotter** [comment]
still not working with Nextcloud 29.0.5

**Comment by smehrbrodt** [comment]
Please update to release 2.0.0, it works now again.

Sorry for the delay. This required a rewrite of the plugin, since the files API changes substantially.

**Comment by hhlotter** [comment]
Thanks for fixing this Works now.
