### ISSUE TITLE
Version 2.0 - takes file association from Nextcloud office

### ISSUE THREAD

**Issue by provelo-ict** [allotropia/nextcloud_files_libreoffice_edit#33]
Sorry, I don't have much time for a full bug report, but I'd like to let you know that after updating to 2.0 all my users where "forced" to open files with Libreoffice instead of Nextcloud Office when single clicking of the file.

They had to use the contextual menu to open with Nextcloud office.

I could not find a switch to toggle that behavior in the settings.

**Comment by AndiDoe** [comment]
same here

**Comment by smehrbrodt** [comment]
Confirm, will investigate.

**Comment by smehrbrodt** [comment]
New release with a fix has been published to Nextcloud Store.

**Comment by alkanex-xyz** [comment]
Thanks. Great :)
