### ISSUE TITLE
Does it only work with Windows? 

### ISSUE THREAD

**Issue by tobefrank1** [allotropia/nextcloud_files_libreoffice_edit#4]
Thank you for your good work.

 
 I installed Collabora office on my systems. It works fine  under windows 10, but not for me under Linux or Android. 

Is there a way to get it to work with the other Systems? 

Thank you.

**Comment by smehrbrodt** [comment]
On Linux/macOS it works starting with upcoming LibreOffice 7.2 ([this commit](https://git.libreoffice.org/core/+/1bc454a2c0cb0dd69512d69ddd2123a44814197e%5E%21) was missing).

I have no idea about Collabora Office, please ask your vendor.

**Comment by tobefrank1** [comment]
I have installed  LibreOffice 7.2 (Beta) and can confirm it is running well, with Linux! 
It also works with Collabora-Office on Windows, but not yet on Linux or Android. 
Would there be a chance to get it working with AndrOpen Office, which is a usable Openoffice version.

**Comment by smehrbrodt** [comment]
> It also works with Collabora-Office on Windows, but not yet on Linux or Android.
> Would there be a chance to get it working with AndrOpen Office, which is a usable Openoffice version.

This is something those vendors need to fix in their versions, the plugin does everything it can do.
Please point your vendor to this commit: https://git.libreoffice.org/core/+/1bc454a2c0cb0dd69512d69ddd2123a44814197e%5E%21
