### ISSUE TITLE
Asking for username and password several times

### ISSUE THREAD

**Issue by harley-peter** [allotropia/nextcloud_files_libreoffice_edit#5]
If I opened a document and try to safe it the app ask me several times for username and password. That does not make sense. It would be enough to ask for the password only when I open a document.

**Comment by smehrbrodt** [comment]
This sounds like a bug in LibreOffice. This extension only provides a link which LibreOffice can open, everything else is handled by LibreOffice.

See the following bugs:
https://bugs.documentfoundation.org/show_bug.cgi?id=140086
https://bugs.documentfoundation.org/show_bug.cgi?id=141086
