### ISSUE TITLE
v1.0.2 in libreoffice 20.0.9 does not open

### ISSUE THREAD

**Issue by christf** [allotropia/nextcloud_files_libreoffice_edit#7]
thanks for building this plugin. On nextcloud 20.0.9 I am using version 1.0.2 of this plugin. When attempting to edit an xls file with the context menu "edit in libreoffice", libreoffice will not open the file and no dialog is shown.
I am using firefox 78.14.0 on debian.

When opening developer tools in the storage tab and selecting the context menu item "edit in libreoffice" I get a yellow warning saying:
"Prevented navigation to “vnd.libreoffice.command:ofe|u|https://mydomain.example.com/myfile?downloadStartSecret=XXXXXXXXXX” due to an unknown protocol."

When trying this in chrome I get a popup that this file is opened with xdg-open.
Then firefox opens and turns up a google search that is showing "not great matches".

When I run xdg-open "just-the-https-bit-from-the-file-url"
then libreoffice opens.

What can I do to further investigate this?

**Comment by smehrbrodt** [comment]
Which LibreOffice version is installed? And how was it installed?

**Comment by christf** [comment]
Am Mon, Nov 08, 2021 at 10:54:27PM -0800 schrieb Samuel Mehrbrodt:
>Which LibreOffice version is installed? And how was it installed?
This is libreoffice 7.0.4 that was installed via apt on debian stable.

As I said, xdg-open http-url opens the file fine in libreoffice so the 
processing in the browser seems to be the culprit here.

**Comment by smehrbrodt** [comment]
You need at least LibreOffice 7.2 on Linux/macOS (see also #4).
You can manually apply the changes in this commit to your .desktop file if you want to keep using 7.0: https://git.libreoffice.org/core/+/1bc454a2c0cb0dd69512d69ddd2123a44814197e%5E%21

I added a hint to the app description about this requirement now, should be visible in the store with the next release.

**Comment by christf** [comment]
thank you @smehrbrodt after applying the patch to the desktop file I can confirm it working even with libreoffice 7.0 on debian stable with chrome. I am being asked for a password to access the file though.

Firefox still shows:
Prevented navigation to “vnd.libreoffice.command:ofe|u|https://nc.xxxxx.de/remote.php/webdavxxxxx.xls?downloadStartSecret=xxxxx” due to an unknown protocol.

**Comment by smehrbrodt** [comment]
> I am being asked for a password to access the file using chrome even though there is a downloadStartSecret passed in the URL. Is this intentional?

I don't know the purpose of this downloadStartSecret. Is that to bypass authentication? If so, something might be missing on the LibreOffice side.

> according to http://kb.mozillazine.org/Register_protocol a protocol must be registered to resolve this issue.

Which Firefox version is that?
For me on Ubuntu with Firefox 94 this worked out of the box.
