### ISSUE TITLE
Libreoffice V7.2.3.2 Linux / Gentoo / Firefox - LO: insufficient access rights

### ISSUE THREAD

**Issue by rotdrop** [allotropia/nextcloud_files_libreoffice_edit#8]
Hi there,

nice idea. I just have upgraded to LO v7.2. Apparently, LO is started but then prompts with "The object cannot be accessed
due to insufficient user rights." When I run the FF Dev-Tools I see that the link is
```
vnd.libreoffice.command:ofe|u|https://anaxagoras.home.claus-justus-heine.de/nextcloud-git/remote.php/webdav/Neues%20Dokument.odt?downloadStartSecret=tcc26hsizhj
```
So this is probably rather a Libreoffice problem. Maybe someone knows how to trigger LO to prompt me for a password? I have already verified respectively wiped the stored password within LO.

Thanks Claus

**Comment by smehrbrodt** [comment]
Which OS is that?
Note that this currently does not seem to work on macOS.

**Comment by smehrbrodt** [comment]
> Which OS is that?

Sorry I missed the bugtitle - it says Gentoo.

You could try with a fresh LibreOffice user profile: `libreoffice --safe-mode`, choose "Run in safe mode". 

Or maybe try if a newer LO version meanwhile fixed the problem?

**Comment by rotdrop** [comment]
Hi, finally found the time to look at it again. It works (now on Ubuntu Jammy) with a fresh install for Libreoffice 7.4. LO prompts for username and password and then opens the file, it is just working fine.
